### PR TITLE
Fixed multiple bugs on file headers update

### PR DESCRIPTION
**Pull request by lflender**
- Fixed header replacement management: if a header is already present and a new one is added in another place using the "Replace" option, then the old one is removed.
e.g. if a header is present at document start and we add a new one after usings with the Replace option, the one at document start is now removed
- Header update on files with no header and no using is now working
- Header piece being sometimes inserted after header is now fixed

### CODE REVIEW

**Comment by codecadwallader** [comment]
Wonderful, thank you for making these fixes! :)

**Comment by lflender** [comment]
Hey @codecadwallader, could I know when you plan to release the next version? I would like to use CodeMaid in my company with VS2022 and we need my latest changes. Maybe I could help with some bug fixes if you have set some objectives on that?

**Comment by lflender** [comment]
I'm not used to milestones, just read about them... So a new version will be released after a number of PRs have been completed?

**Comment by codecadwallader** [comment]
Hi @lflender , I don't have the next release planned yet.  Your changes should(tm) be available in the CI channel, but that's not as easy for everyone to install/update as an official release.  Some bug fix help would be great as there's definitely been an influx with the new VS2022 support!

The most urgent issue on my mind is that with VS2022 (and VS2019) the insert explicit access modifier APIs are misbehaving.  Several of the recently created issues (e.g. #879 #866) all tie back to this underlying issue.  I think if we had a solution for that it would definitely warrant a release as it would solve several issues.

I mainly use the milestones to link together issues into a release for posterity.  The idea being that if you wanted to see the changes in a specific release you could go to that milestone and see all the issues/PRs that were linked.

Thanks for your help!  Lets use #879 to communicate any progress on the insert explicit access modifier functionality.  That issue has the worst side effect IMO.

**Pull request merged**
