### PR TITLE
Make CodeMaid window disappear in Full screen mode (Alt-Ctrl-Enter)

### PR DESCRIPTION
**Pull request by iouri-s**
Source:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/40556a0b-76b3-494d-b478-0dd4cfb4979f/how-do-i-control-visibility-of-my-tool-windows-in-the-full-screen-mode?forum=vsx

### CODE REVIEW

**Comment by codecadwallader** [comment]
Thanks for the pull request.  :)  I'll take a look at it and give it consideration.

**Comment by codecadwallader** [comment]
I agree it makes sense to have Spade hide while in full screen mode.  Are you familiar with the code you've provided, or is it copy/paste from an MSDN forum?  I'm not sure how it will react in all scenarios (e.g. when you come out of full screen mode, does the tool window restore?) and was curious how much you could explain what it's doing.

**Comment by iouri-s** [comment]
Hi Steve,
I found it annoying that the spade window stayed up while solution and team explorers went away. So I found this solution on the internet and it made sense. I tested it under the debugger and it worked correctly - the window reappeared in its docked location when I exited the full screen mode. I have been using my private build of a week and did not find any adverse effects.

Regards,
Iouri

Sent from Outlook Mobile<https://aka.ms/blhgte>

**Comment by codecadwallader** [comment]
I pulled this down, and it worked for me in a quick test in VS2015.  Also looked up the API and it seemed like the intended use for it.

Did you test this against VS2015?  How about any of the other supported versions (i.e. VS2012, VS2013)?

I'd also like to do some minor code cleanup (e.g. null reference handling if the service isn't available), but other than that should be able to move forwards with accepting it.

**Comment by iouri-s** [comment]
Hi Steve, I use VS 2015 Update 1 (14.0.24713.00). Just tried it on VS 2013 Update 4 (12.0.31101.00) and it also works fine.

Thanks,
iouri

**Comment by codecadwallader** [comment]
@iouri-s Thanks again for this pull request, it's been merged and will be present in the next beta release. Do you mind if I credit you during the next release's blog post?

**Comment by iouri-s** [comment]
I would be home.

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Sat, Jan 30, 2016 at 10:57 AM -0800, "Steve Cadwallader" <notifications@github.com<mailto:notifications@github.com>> wrote:


@iouri-s<https://github.com/iouri-s> Thanks again for this pull request, it's been merged and will be present in the next beta release. Do you mind if I credit you during the next release's blog post?

-

**Comment by iouri-s** [comment]
I mean "I would be honored". And "I am learning how to use a smartphone".

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Sat, Jan 30, 2016 at 10:57 AM -0800, "Steve Cadwallader" <notifications@github.com<mailto:notifications@github.com>> wrote:


@iouri-s<https://github.com/iouri-s> Thanks again for this pull request, it's been merged and will be present in the next beta release. Do you mind if I credit you during the next release's blog post?

-

**Comment by codecadwallader** [comment]
Hehe.. nice. ;)

**Pull request merged**
