### PR TITLE
Modernized object initialization syntax to avoid redundancy (that is, I used `new()`)

### PR DESCRIPTION
**Pull request by Lehonti**
As an extra, I added a `readonly` modifier to a couple of fields that were never changed

### CODE REVIEW

**Comment by Lehonti** [comment]
@codecadwallader any plans to merge this? It's a quick and easy way to improve the code

**Comment by codecadwallader** [comment]
Thank you for making this suggestion, I'm sorry I did not get back to you sooner.

**Comment by Lehonti** [comment]
No problem, @codecadwallader should I re-open it?

**Comment by codecadwallader** [comment]
Yes, you're welcome to re-open it.

**Pull request closed without merging**
