### PR TITLE
Implemented RadialProgressBar in SpadeToolbar

### PR DESCRIPTION
**Pull request by Jammer77**

### CODE REVIEW

**Comment by Jammer77** [comment]
How to delete TEST commit?

**Comment by codecadwallader** [comment]
I haven't used them, but rebase and cherry-pick are a couple commands I've heard in that space if you want to investigate them.  A simpler approach may be to make another commit that undoes whatever changes are in your test commit.  The pull request will then reflect the canceled out changes.

**Comment by Jammer77** [comment]
You are happy, is it a cool control?

**Comment by Jammer77** [comment]
Can you merge? Or you need something?

**Comment by codecadwallader** [comment]
I appreciate your enthusiasm.  It does look like it will be cool.  I haven't pulled it down locally yet to test it, but a couple items that I'd appreciate having resolved:

1.  The TEST commit you put in with unwanted code changes needs to be cleaned up.  See comments above about a couple possible approaches.
2.  There is a mismatch between a WidthConverter file with a CenterConverter class in it.  Since this converter is only dividing by two, lets please call both the file and the class a HalfConverter so it may be clearer to others.

**Comment by Jammer77** [comment]
Ok

**Comment by Jammer77** [comment]
Now you can merge :)

**Comment by Jammer77** [comment]
🥇

**Comment by codecadwallader** [comment]
That looks awesome!!  Thanks so much for doing that!  Merging now. :D

**Comment by Jammer77** [comment]
Thanks for your great tool!!!

**Pull request merged**
